### ISSUE TITLE
Attribute "lineWidth" has already been defined

### ISSUE THREAD

**Issue by IGZpablocanamares** [TakWolf/Android-Lock9View#1]
I have a few libs in my project, and another one use the same lineWidth attribute. When try to compile with gradle, this error appear.

The issue is that there is a single namespace for all resource names and both libraries are colliding. This is clearly not great at all, I understand your frustrations, but until the platform implements the ability to have different resource pools inside an app there's little the tools can do.

The only options are:
- prefix attributes with a name unique

**Comment by TakWolf** [comment]
Got it. Gave me some time to fix it.

**Comment by TakWolf** [comment]
Have fixed with 0.0.4.
Thank you very much!

**Comment by IGZpablocanamares** [comment]
:+1: And thank you!
