### ISSUE TITLE
跳跃连线

### ISSUE THREAD

**Issue by esirong** [TakWolf/Android-Lock9View#7]
即连接线所经过的点没有被选中。
可以增加这项设置吗？连线所经过的点都是被选中的。

**Comment by TakWolf** [comment]
可以，需要点时间

**Comment by TakWolf** [comment]
已经添加，更新到版本 0.0.9

    compile 'com.takwolf.android:lock9view:0.0.9'

在布局中添加属性：

    app:lock9_autoLink="true"
